### ISSUE TITLE
ErrorException in Connection.php line 770

### ISSUE THREAD

**Issue by nke69** [LiddleDev/LiddleForum#4]
Hi 
i've got an error when i browse categories.
Can you help me ?
Thx ;)

1/3 ErrorException in Connection.php line 770: SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause (SQL: select count(*) as aggregate from `liddleforum_categories` where `liddleforum_categories`.`parent_id` = 10 and `liddleforum_categories`.`parent_id` is not null order by `order` asc) (View: D:\DEV\psb.nke69.be\resources\views\vendor\liddleforum\categories\view.blade.php)

 2/3 QueryException in Connection.php line 770: SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause (SQL: select count(*) as aggregate from `liddleforum_categories` where `liddleforum_categories`.`parent_id` = 10 and `liddleforum_categories`.`parent_id` is not null order by `order` asc) 

 1/3 PDOException in Connection.php line 333: SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause

**Comment by tomgrohl** [comment]
It sounds like your using mysql 5.7. And the `ONLY_FULL_GROUP_BY` settings is turned on.

If you turn it off that should sort the issue your having.

More info here: https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by

**Comment by tomgrohl** [comment]
Also depending on the version of Laravel used, they might be turning this feature on. See https://github.com/laravel/framework/issues/14997#issuecomment-242129087 for more info

**Comment by tomgrohl** [comment]
As there has been no response I'll close this issue. Feel free to open it if your still having problems.

**Comment by nke69** [comment]
Hi tom,

I followed the recommendations of the following article: https://github.com/laravel/framework/issues/14997#issuecomment-242129087
That said, I also modify my SQL config as per my needs.
Thank you again for the follow up of my request;)

Cordially.
